### ISSUE TITLE
send emails at relevant points

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#139]
Since 8cfd3e5784a4ec15cd55d3e20bca88cb50603559 a mail system is in place to send email when a new admin is added. Extend this system with mails for:
- New participant, send to all project admins
- New signup, send to COMIC_admins
- Created new project, send to creator
- Registration complete, send to registrated user, remind them how to log in. (or does this happen already?)

**Comment by jmsmkn** [comment]
Continued in #227
