### ISSUE TITLE
setting unix file permissions right

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#198]
Any file or dir written by django itself has owner and group 'comicftp'
Any file served by apache through xsendfile needs user or group 'www-data' 

This sometimes causes problems, for example when uploading via the page editor, xsendfile is used. If the upload dir has been created by comicftp, www-data cannot write to this dir.

How to handle access for both systems? 
Maybe create a group comicframework containing comicftp and www-data and write everything as this group? 

This python code shows how to change group of a file or dir to 'www-data'

``` python
import os
from pwd import getpwnam

os.chown("/srv/home/comicftp/Dropbox/comicframework/VESSEL12/uploads/testperm.txt",-1,getpwnam('www-data')[2])
```

However this operation is not permitted. Can we give chown permission to user comicftp inside certain directories?

**Comment by jmeakin** [comment]
Solved with the docker based deployment.
