### ISSUE TITLE
Request computation by writing request files. 

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#246]
Results like http://localhost:8000/site/anode09/result/?id=5-7-combined
are now rendering precomputed graphs.

These combinations should be computed on the fly. On way to do this cleanly is this:
when a user calls a url
http://localhost:8000/site/anode09/result/?id=5-7-combined

It is checked whether this result exists. If not, a file is written to the project data folder, containing a request to combine method 5 and 7. This file is read by some kind of request checking deamon, which reads the file, runs an executable and when output is done, removes the request file.
In the mean time the webpage should display something like "Computing, please refresh the page in xx seconds"

Advantage of writing files is that is is architecture independent and versatile.

**Comment by jmsmkn** [comment]
wontfix
