### ISSUE TITLE
Webrendering does not work on most public networks, probably because of port issues

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#247]
When on a public network or a guest network, 
http://comicframework.org/visualisation_example/

does not work, as a connection to the visualization server needs to be established over a non standard port. This port is often blocked.

Is this easily fixed or is this a fundamental problem? I am unsure of this.

**Comment by jmeakin** [comment]
Visualisation things have been removed from COMIC. For mevis we know how to do this now - everything on https.
