### ISSUE TITLE
uploaded files should have user or group compatible with dropboxclient

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#259]
Right now uploaded files will have owner and group set by the django server user, which is different than the user running the dropbox client. This causes problems sometimes with dropbox client not being able to delete or move files.

What to do about this?

Some thoughts:
- Have dropboxclient run under django server user (sounds a bit icky) 
- Set group to dropbox client user explicitly in django
- Can you have something like sticky groups or someting in linux where any file put into a dir will have a certain group?

**Comment by jmeakin** [comment]
We no longer have SFTP on the server
