### ISSUE TITLE
redirect after gmail login is again wrong, not using subdomain as projectname

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#283]
For example

From http://caddementia.grand-challenge.org/ I click sign in, the url will be 
http://caddementia.grand-challenge.org/accounts/signin/?next=/home/
and after logging in using google I will be redirected to the main grand-challenge.org home page instead of the CADDementia page. This worked correctly before

**Comment by jmsmkn** [comment]
Fixed
