### ISSUE TITLE
MySQL connection lost at times

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#299]
Recently, July 30th, 2015,10:45,  this error occurred:
OperationalError: (2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 104")

What does this mean? Check this out

**Comment by sjoerdk** [comment]
Same error Thursday 6:21 PM
OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)")

**Comment by jmeakin** [comment]
Not seen on the new system in the past 7 days. Tentatively closing.
