### ISSUE TITLE
Grandchallenge.com Server 500 Error while file uploading

### ISSUE THREAD

**Issue by PatrickChrist** [comic/comic-django#301]
Hey Guys,

I creating a challenge and wanted to upload files to change the layout. When i hit the upload button I will be forwarded to the a blank page with Error 500.

Do you have any ideas?

Thanks,
Patrick

**Comment by jmeakin** [comment]
Hi Patrick,

Sorry this query went unanswered, the project was not being maintained at the time. File uploading works again now, please get in touch with me if you would like to try using grand-challenge for your next challenge.
