### ISSUE TITLE
After google signin, redirect to last page is wrong (not using custom hostname)

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#302]
To recreate:

* Go to https://lola11.grand-challenge.org/download/ while not logged in. This will display "You need to log in to see this page"
* Click Sign in / Register button on top left. This will take you to https://lola11.grand-challenge.org/accounts/signin/?next=/download/
* Click the google button and go through the procedure there
* You are redirected to https://grand-challenge.org/download/ (without the lola11 in front) which does not exist.

**Comment by jmsmkn** [comment]
Fixed.
