### ISSUE TITLE
Implement challenge participant workflow

### ISSUE THREAD

**Issue by jmsmkn** [comic/comic-django#371]
1. Participant uploads a new `submission`
2. For this `submission`, a new `job` is created using the most recent `method` for that `challenge`
3. The `job` is registered with the `scheduler`
4. On success, a new `result` is created
5. In all cases, the challenge participant and administrator are emailed

**Comment by jmeakin** [comment]
We should be able to hide and unhide results, set by the participant and admin.

**Comment by jmsmkn** [comment]
Fixed.
