### ISSUE TITLE
Implement job runner and scheduler

### ISSUE THREAD

**Issue by jmsmkn** [comic/comic-django#372]

**Comment by jmeakin** [comment]
Components needed: `registry`, `scheduler factory`, `nomad scheduler`

**Comment by jmeakin** [comment]
**registry authorisation**

1. Only challenge admins can `push` new images with the tag for that challenge. 
2. Reproducibility requirement: Images cannot be overwritten/updated, a new version must be created. The use of `latest` is forbidden.
3. The current evaluation container is selected from the available containers in the registry. 
4. Only the evaluation server can `pull` images.

**Comment by jmeakin** [comment]
Our scale is too small for Nomad (requires 3+ servers for fallover protection), and previous experience with Celery has been great but docker tasks were not part of this. Girder worker and Apache Airflow were both candidates for higher level job management (ie, they at least support having celery workers run docker containers). However, at this moment neither support authenticated registries, and girder worker is python 2 only. So, I will run with Celery and add the docker component on top.

**Comment by jmsmkn** [comment]
Fixed.
