### ISSUE TITLE
executing algorithms on uploaded data - first version

### ISSUE THREAD

**Issue by sjoerdk** [comic/comic-django#7]
Algorithms pertains to both image processing and evaluation of submitted results.
The quickest way to implement this without coding ourselves into a corner is to use the method now used by BIGR and DIAG for their challenges:  Give organizers the ability to download upladed data, have them process it themselves and upload the results.

With a few scripts on the organizers side this will already be automated processing.

**Comment by jmsmkn** [comment]
Fixed
